default:
	javac *.java

run:
	java Main

clean:
	rm -f *.class
	reset
	clear

tar:
	tar -cvz DatabaseException.java Database.java Node.java Cell.java Treap.java -f Code.tar.gz

unZip_unTar:
	tar -zxvf Code.tar.gz